### PR TITLE
implement schedule page

### LINKED ISSUE #3: Create page for each classroom
Requirements:
- [x] should be responsive
- [x] mobile:  each day in a page with swipe gesture to switch between days in a horizontal manner.
- [x] show free and occupied slots on a calendar like background
- [x] color of free slots should match letter color

Figma design:
https://www.figma.com/file/C3xRUtPirmcLDFhqiJwVeH/Tuwaiq-Classrooms?node-id=22%3A275

### PR DESCRIPTION
**Pull request by YazeedAlKhalaf**
This PR implements the schedule page.

### CODE REVIEW

**Review by ghost — DISMISSED** [review]
LGTM

**Review by MaissaAlbaik — DISMISSED** [review]
The code works very well and is running smoothly.

**Comment by YazeedAlKhalaf** [comment]
@g9wz @MaissaAlbaik 
kindly review the new changes whenever you are free.

**Review by ghost — APPROVED** [review]
looks good for now

**Pull request merged**
